name: thetale_api
description: "An implementation of https://the-tale.org api in Dart."
version: 1.0.0
homepage: https://github.com/ariedov/thetale_api_dart
author: David Leibovych <ariedov@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: ^3.0.1
  test_coverage: ^0.2.0

